apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: email-service
spec:
    replicas: 1
    template:
        metadata:
            labels:
              app: email-service
              tier: backend
        spec:
            containers:
            - name: email-service
              image: sleepingtalent/email-service:1.0.17
              readinessProbe:
                httpGet:
                  path: /email-service/info
                  port: 2222
                initialDelaySeconds: 120
                timeoutSeconds: 60
                periodSeconds: 15
              livenessProbe:
                httpGet:
                  path: /email-service/info
                  port: 2222
                initialDelaySeconds: 120
                timeoutSeconds: 60
                periodSeconds: 15
              env:
              - name: CONFIG_URL
                value: http://config-api-gateway:1111/config-api/
              ports:
              - containerPort: 2222
---

apiVersion: v1
kind: Service
metadata:
    name: email-service-gateway
    labels:
        app: email-service
        tier: backend
spec:
    type: LoadBalancer
    ports:
    - port: 2222
    selector:
        app: email-service
        tier: backend


