apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: email-service
spec:
    replicas: 1
    template:
        metadata:
            labels:
              app: email-service
              tier: backend
        spec:
            containers:
            - name: email-service
              image: sleepingtalent/email-service:1.0.6
              env:
              - name: CONFIG_URL
                value: http://10.52.180.42:1111/config-api/
              ports:
              - containerPort: 2222

