###############################################################
### Default Configuration for development environment       ###
### This file with be used on local dev and CI environments ###
###############################################################
version: '2'

services:

  test-smtp-server:
        image: mailhog/mailhog
        ports:
          - "1025:1025"
          - "8025:8025"
        expose:
          - "1025"
          - "8025"
  #http://localhost:8025

  email-service:
      image: sleepingtalent/email-service:snapshot
      environment:
      - SERVER_PORT=2222
      - SPRING_PROFILES_ACTIVE=test
      ports:
      - "2222:2222"
      depends_on:
      - test-smtp-server
      command: ["dockerize", "-wait", "http://config-api:1111/config-api/email-service/test", "-wait", "http://test-smtp-server:8025", "-wait", "http://rabbitmq:15672","-timeout", "380s", "--", "/bin/sh", "-c", "java -jar app.jar --server.port=2222 --spring.profiles.active=test --spring.cloud.config.uri=http://config-api:1111/config-api/"]
      volumes:
       - /home/developer/docker-logs/:/app/log
      expose:
       - "2222"
  #http://localhost:2222/email-service/info

networks:
  default:
    external:
      name: infrastructure_microservices
